apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: cloudhub
  labels:
      app: telegraf
data:
  telegraf.conf: |+
    [agent]
      debug = true
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "1m"
      flush_jitter = "10s"
      omit_hostname = false

    [[outputs.influxdb]]
      urls = [ "http://10.20.2.51:8086" ]
      database = "RnD"
      username = ""
      password = ""
      retention_policy = ""
      write_consistency = "any"
      timeout = "10s"

    [[inputs.cpu]]
      percpu = false
      totalcpu = true
      collect_cpu_time = false
      report_active = false

    [[inputs.kubernetes]]
      interval = "1m"
      ## URL and port for the kubelet
      url = "https://localhost:10250"
    
      ## Use bearer token for authorization. ('bearer_token' takes priority)
      ## If both of these are empty, we'll use the default serviceaccount:
      ## at: /run/secrets/kubernetes.io/serviceaccount/token
      # bearer_token = "/path/to/bearer/token"
      ## OR
      bearer_token_string = "$token"
    
      ## Pod labels to be added as tags.  An empty array for both include and
      ## exclude will include all labels.
      # label_include = []
      # label_exclude = ["*"]
    
      ## Set response_timeout (default 5 seconds)
      response_timeout = "20s"
    
      ## Optional TLS Config
      # tls_ca = /path/to/cafile
      #tls_cert = "/var/lib/minikube/certs/apiserver-kubelet-client.crt"
      #tls_key = "/var/lib/minikube/certs/apiserver-kubelet-client.key"
      ## Use TLS but skip chain & host verification
      insecure_skip_verify = true 
